services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${DB_NAME:-mydatabase}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD:-secret}'
      - 'POSTGRES_USER=${DB_USER:-user}'
    ports:
      - '${DB_PORT:-5432}:5432'
    env_file:
      - ./.env
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT:-5050}:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT:-5050}
    env_file:
      - ./.env